### ISSUE TITLE
ModuleNotFoundError: No module named 'CCC'

### ISSUE THREAD

**Issue by pratikm141** [leokarlin/LaSO#3]
When I run the code 

python train_setops_stripped.py --inception_transform_input=False --resume_path=LaSO_mode
ls/resnet_base_model_only --resume_epoch=49 --init_inception=False --sets_basic_block_name=SetopResBasicBlock --sets_block_name=SetopResBlock_v
1 --sets_network_name=SetOpsResModule --ops_latent_dim=8092 --ops_layer_num=2 --base_network_name=resnet50 --crop_size=224 --epochs=50 --train_
base=False --coco_path='~/data_local/coco' --results_path='./results/'

I get this error:
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_setops_stripped.py", line 32, in <module>
    from CCC import setupCUDAdevice
ModuleNotFoundError: No module named 'CCC'

**Comment by alfassy** [comment]
Hi,
You can remove the import to CCC and also remove the use of the setupCUDAdevice fuction.
I will change it to commented out in the official release as well.
Let me know if the problem is solved please.

Regards,
Amit

**Comment by pratikm141** [comment]
Thanks the issue is resolved

**Comment by punitha-valli** [comment]
As you mentioned in the paper,
Zint=Mint(Fx,Fy)
Zuni=Muni(Fx,Fy)

If i applied this equation to the Rsymmentrical Loss, the finall answer will be zero.

Can you please tell me about these Losses.

**Comment by alfassy** [comment]
Hi,
as can be seen in the implementation, the input to each of the 3 set operation networks is a concatenation of two feature vectors, for example Fx and Fy, we wish to get the same resulting feature vector in the output of each of the intersection and union networks when we concatenate Fx to Fy or when we concatenate Fy to Fx. meaning regardless of which feature vector is first in the concatenation. This is exactly the Rsymmetrical loss.
I hope this helps.

**Comment by punitha-valli** [comment]
hi,
am little bit confused about the code- implementation.
Can you please guide me ?, that how to implement LASO.

Thanks in advance.

**Comment by punitha-valli** [comment]
Traceback (most recent call last):
  File "G:/yzu/lab/1st sem/laso/zip/LaSO-master/scripts_coco/train_setops_stripped.py", line 17, in <module>
    from oneshot.coco import copy_coco_data
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\oneshot\__init__.py", line 4, in <module>
    from .fitBeamlineScan import *           # noqa
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\oneshot\fitBeamlineScan.py", line 8, in <module>
    import scisalt.scipy as _ssc
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\scisalt\__init__.py", line 6, in <module>
    from . import accelphys
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\scisalt\accelphys\__init__.py", line 11, in <module>
    from .fitimageslice import fitimageslice
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\scisalt\accelphys\fitimageslice.py", line 6, in <module>
    from .. import scipy as _sp
  File "C:\Users\Labpc\AppData\Local\Continuum\anaconda3\lib\site-packages\scisalt\scipy\__init__.py", line 23, in <module>
    from .hough_ellipse import hough_ellipse
ModuleNotFoundError: No module named 'scisalt.scipy.hough_ellipse'


while implementing i usually get this error
